USE [master]
GO

/****** Object:  Database [$database-name$]    Script Date: 25/06/2018 09:49:10 ******/
CREATE DATABASE [$database-name$]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'$database-name$', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\$database-name$.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'$database-name$_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\$database-name$_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [$database-name$] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [$database-name$].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [$database-name$] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [$database-name$] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [$database-name$] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [$database-name$] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [$database-name$] SET ARITHABORT OFF 
GO

ALTER DATABASE [$database-name$] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [$database-name$] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [$database-name$] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [$database-name$] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [$database-name$] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [$database-name$] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [$database-name$] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [$database-name$] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [$database-name$] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [$database-name$] SET  DISABLE_BROKER 
GO

ALTER DATABASE [$database-name$] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [$database-name$] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [$database-name$] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [$database-name$] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [$database-name$] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [$database-name$] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [$database-name$] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [$database-name$] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [$database-name$] SET  MULTI_USER 
GO

ALTER DATABASE [$database-name$] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [$database-name$] SET DB_CHAINING OFF 
GO

ALTER DATABASE [$database-name$] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [$database-name$] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [$database-name$] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [$database-name$] SET QUERY_STORE = OFF
GO

USE [$database-name$]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [$database-name$] SET  READ_WRITE 
GO


